apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2board.fullname" . }}-nginx
  labels:
    app: {{ include "v2board.name" . }}-v2board-web
    {{- include "v2board.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "v2board.name" . }}-v2board-web
    {{- include "v2board.selectorLabels" . | nindent 4 }}
