{{- if .Values.nfs.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "v2board.fullname" . }}-nfs-server
  labels:
    app: {{ include "v2board.name" . }}-nfs-server
    {{- include "v2board.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "v2board.name" . }}-nfs-server
  template:
    metadata:
      labels:
        app: {{ include "v2board.name" . }}-nfs-server
    spec:
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            {{- if .Values.nfs.persistence.existingClaim }}
            claimName: {{ .Values.nfs.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "v2board.fullname" . }}-nfs-pvc
            {{- end }}
      containers:
        - name: nfs-server
          image: {{ .Values.nfs.image.repository }}:{{ .Values.nfs.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: mountd
              containerPort: 20048
              protocol: TCP
            - name: rpcbind
              containerPort: 111
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nfs-pvc
              mountPath: /exports
            - name: nfs-pvc
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

{{- end }}
