{{ if .Values.nfs.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "v2board.fullname" . }}-nfs
  labels:
    app: {{ include "v2board.name" . }}-nfs-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.persistence.size }}
  volumeName: {{ .Release.Namespace }}-{{ include "v2board.fullname" . }}-nfs
  storageClassName: ''
  volumeMode: Filesystem
{{ end }}
