kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "v2board.fullname" . }}-schedule
  labels:
    app: {{ include "v2board.fullname" . }}-schedule
    {{- include "v2board.labels" . | nindent 4 }}
spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: {{ include "v2board.fullname" . }}-schedule
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 300
      backoffLimit: 3
      template:
        metadata:
          name: {{ include "v2board.fullname" . }}-schedule
          labels:
            app: {{ include "v2board.fullname" . }}-schedule
            {{- include "v2board.labels" . | nindent 12 }}
        spec:
          volumes:
            - name: config-data
              persistentVolumeClaim:
                claimName: {{ include "v2board.fullname" . }}-nfs
          containers:
            - name: {{ include "v2board.fullname" . }}-schedule-cron
              image: {{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}
              imagePullPolicy: IfNotPresent
              command:
                - sh
              args:
                - /entrypoint_cron.sh
              env:
                - name: APP_DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: APP_DEBUG
                - name: APP_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: APP_KEY
                - name: APP_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: APP_NAME
                - name: APP_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: APP_URL
                - name: DB_CONNECTION
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: DB_CONNECTION
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: DB_DATABASE
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: DB_PORT
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: REDIS_HOST
                - name: REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: REDIS_PORT
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "v2board.fullname" . }}-redis
                      key: redis-password
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "v2board.fullname" . }}-mariadb
                      key: mariadb-password
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "v2board.fullname" . }}-env
                      key: DB_USERNAME
              resources: {}
              volumeMounts:
                - name: config-data
                  mountPath: /data/v2board/config
                  subPath: config
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 60
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
