kind: Job
apiVersion: batch/v1
metadata:
  name: {{ include "v2board.fullname" . }}-install
  labels:
    app: {{ include "v2board.fullname" . }}-install
  annotations:
    batch.kubernetes.io/job-tracking: ''
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 600
  backoffLimit: 1
  selector:
    matchLabels:
      job-name: {{ include "v2board.fullname" . }}-install
  template:
    metadata:
      name: {{ include "v2board.fullname" . }}-install
      labels:
        job-name: {{ include "v2board.fullname" . }}-install
    spec:
      volumes:
        - name: config-data
          persistentVolumeClaim:
            claimName: {{ include "v2board.fullname" . }}-nfs
      containers:
        - name: {{ include "v2board.fullname" . }}-installer
          image:  {{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}
          command:
            - sh
          args:
            - /entrypoint_artisan_job.sh
            - 'v2board:install'
          env:
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: APP_DEBUG
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: APP_KEY
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: APP_NAME
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: APP_URL
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: DB_CONNECTION
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: DB_DATABASE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: DB_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: REDIS_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-password
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "v2board.fullname" . }}-env
                  key: DB_USERNAME
            - name: DEFAULT_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: v2board-install-config
                  key: DEFAULT_ADMIN_EMAIL
          resources: {}
          volumeMounts:
            - name: config-data
              mountPath: /data/v2board/config
              subPath: v2board/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false
